### ISSUE TITLE
ToJSON errors when called on elements

### ISSUE THREAD

**Issue by John-Boik** [dss-extensions/OpenDSSDirect.jl#102]
It appears that the element.ToJSON() function is not working properly, or at least not working as I expect. Apparently, it should be called with an Int64, but this throws a `UndefVarError: `getstring` not defined` error.

Here is an example, using the simple DSS file from Issue [101](https://github.com/dss-extensions/OpenDSSDirect.jl/issues/101), where the file is saved as filename.dss:

```
import OpenDSSDirect as DSS
DSS.Basic.AllowEditor(false)
DSS.dss("""
    clear
    redirect "filename.dss"
    """)

DSS.Transformers.First()
1

infil> DSS.Element.Name()
"Transformer.tx1"

infil> DSS.Element.ToJSON()
ERROR: MethodError: no method matching ToJSON()

Closest candidates are:
  ToJSON(::Int64)
   @ OpenDSSDirect ~/.julia/packages/OpenDSSDirect/TOPxW/src/element.jl:41
  ToJSON(::OpenDSSDirect.DSSContext, ::Int64)
   @ OpenDSSDirect ~/.julia/packages/OpenDSSDirect/TOPxW/src/element.jl:38

infil> DSS.Element.ToJSON(0)
ERROR: UndefVarError: `getstring` not defined
Stacktrace:
 [1] ToJSON(dss::OpenDSSDirect.DSSContext, Flags::Int64)
   @ OpenDSSDirect.Element ~/.julia/packages/OpenDSSDirect/TOPxW/src/element.jl:39
 [2] ToJSON(Flags::Int64)
   @ OpenDSSDirect.Element ~/.julia/packages/OpenDSSDirect/TOPxW/src/element.jl:41
```
The same error occurs with other Int64s, such as ToJSON(1). I suspect it should accept an Int32, rather than Int64. For example, this works: `DSS.Circuit.ToJSON(Int32(1))`.

@PMeira, thanks for your help and the excellent explanation on Issue 101. I thought I would also create an issue for this ToJSON problem in case you want to include a fix in the upcoming release.

**Comment by PMeira** [comment]
Sorry, @John-Boik, forgot to push the commit earlier. Fixed and added tests for that function for v0.9.9. We're planning an engine update for next week.
