### ISSUE TITLE
Support matrix instead of vector of float64

### ISSUE THREAD

**Issue by kdheepak** [dss-extensions/OpenDSSDirect.jl#43]
Currently, the Lines.RMatrix functions accept and return a vector of floats. But they can accept / return a Matrix instead

```
    """Resistance matrix (full), ohms per unit length. Array of doubles. (Getter)"""
    function RMatrix()::Matrix{Float64}
        n = Phases()
        if n == 0
            rmatrix = Matrix{Float64}[]
        else
            rmatrix = reshape(Utils.get_float64_array(Lib.Lines_Get_Rmatrix), (n, n))
        end
        return rmatrix
    end

    """Resistance matrix (full), ohms per unit length. Array of doubles. (Setter)"""
    function RMatrix(Value::Matrix{Float64})
        n = Phases()
        RMatrix(reshape(Value, (n * n, 1)))
    end

    """Resistance matrix (full), ohms per unit length. Array of doubles. (Setter)"""
    function RMatrix(Value::Vector{Float64})
        Value, ValuePtr, ValueCount = Utils.prepare_float64_array(Value)
        Lib.Lines_Set_Rmatrix(ValuePtr, ValueCount)
    end

```

Alternatively, we can accept/return as a `Matrix{ComplexF64}` instead. RMatrix in this case would be just reals. XMatrix can be just imaginary values in this matrix. I'd prefer just returning a Matrix{Float64} and letting users deal with converting it to the corresponding complex numbers.

Thoughts?

**Comment by tshort** [comment]
I agree with your preference. We could also add a `ZMatrix` function that returns both as a complex matrix.

**Comment by kdheepak** [comment]
Should ZMatrix return `R +jX` or `R + jX + jC`?

**Comment by tshort** [comment]
R + j X
