### ISSUE TITLE
Build error with Julia-1.3.0 on Windows

### ISSUE THREAD

**Issue by stroitzsch** [dss-extensions/OpenDSSDirect.jl#52]
I'm getting a build error in when trying to build OpenDSSDirect.jl with Julia-1.3.0 on Windows:

```
┌ Error: Error building `OpenDSSDirect`: 
│ ERROR: LoadError: IOError: could not spawn `'C:\Users\username\AppData\Local\Julia-1.3.0\bin/7z' x 'C:\Users\username\.julia\packages\OpenDSSDirect\wldy1\deps\dss_capi.zip' -y '-oC:\Users\username\.julia\packages\OpenDSSDirect\wldy1\deps'`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
│  [2] setup_stdios(::Base.var"#554#555"{Cmd}, ::Array{Any,1}) at .\process.jl:112
│  [3] success(::Cmd) at .\process.jl:111
│  [4] download(::Type{Windows}) at C:\Users\username\.julia\packages\OpenDSSDirect\wldy1\deps\build.jl:64
│  [5] top-level scope at C:\Users\username\.julia\packages\OpenDSSDirect\wldy1\deps\build.jl:84
│  [6] include at .\boot.jl:328 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1105
│  [8] include(::Module, ::String) at .\Base.jl:31
│  [9] include(::String) at .\client.jl:424
│  [10] top-level scope at none:5
│ in expression starting at C:\Users\username\.julia\packages\OpenDSSDirect\wldy1\deps\build.jl:84
│ url = "https://github.com/dss-extensions/dss_capi/releases/download/0.10.1/dss_capi_0.10.1_win_x64.zip"
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
```

This may be related to `7z` having been moved in Julia-1.3.0: https://github.com/JuliaLang/julia/pull/33493

**Comment by kdheepak** [comment]
Thanks for reporting the error! I've added the latest version of Julia to our tests, fixed this issue and cut a new release. Once v0.6.0 is tagged, you should be able to `update` the `OpenDSSDirect` package and get the latest version where this is fixed. If it still does not work / you find something else is going on, feel free to reopen this issue.

**Comment by kdheepak** [comment]
You should be able to try it now.

**Comment by stroitzsch** [comment]
Works now, thanks for the prompt fix!

**Comment by stroitzsch** [comment]
However, to let you know, I've got this error:

```
add OpenDSSDirect@0.6.0
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package OpenDSSDirect [a8b11937]:
 OpenDSSDirect [a8b11937] log:
 ├─possible versions are: [0.5.0-0.5.1, 0.6.0] or uninstalled
 ├─restricted to versions 0.6.0 by an explicit requirement, leaving only versions 0.6.0
 └─restricted by compatibility requirements with DocStringExtensions [ffbed154] to versions: 0.5.0-0.5.1 or uninstalled — no versions left
   └─DocStringExtensions [ffbed154] log:
     ├─possible versions are: [0.4.6, 0.5.0, 0.6.0, 0.7.0, 0.8.0-0.8.1] or uninstalled
     └─restricted to versions 0.8.1 by an explicit requirement, leaving only versions 0.8.1
```

Which was resolved by downgrading DocStringExtensions on my side: `add DocStringExtensions@0.6.0` and then `add OpenDSSDirect@0.6.0`.

It's related to this change: https://github.com/dss-extensions/OpenDSSDirect.jl/commit/d6494b007abe70f2a4a2ff9b589dff7d07877f15#diff-910a7b3ca0075d545dcec45cb7335ca9R7 although the behavior of Pkg doesn't seem consistent with its documentation: https://julialang.github.io/Pkg.jl/v1/compatibility/index.html#Version-specifier-format-1

A bug in Pkg?

**Comment by kdheepak** [comment]
That is an odd error. Regardless, I can decrease the upper bound requirement for this package.

**Comment by kdheepak** [comment]
Can you try now with v0.6.1?

**Comment by stroitzsch** [comment]
Works now without further issues. Thanks again!
