### ISSUE TITLE
How to access attributes of multiple circuit elements?

### ISSUE THREAD

**Issue by asavasci** [dss-extensions/OpenDSSDirect.jl#80]
I am trying to access a specific generator element to set/get its attribute values. When I defined multiple generators and wanted to set/get their attributes individually or collectively. The DSS.Generator.Function() only sets/gets the information that belongs to the last generator defined in the DSS file.  For example I define two generators in the system as 
```
New` Generator.GEN671  Bus1=671  kV=4.16 kW=200 Pf=1  Model=1 conn=3
New Generator.GEN680  Bus1=680  kV=4.16 kW=100 Pf=0.95  Model=1 conn=3 
```

After compiling the circuit, and using `DSS.Generator.kW()`, it only returns 100 which is GEN680's kWrating. I have also tried  
```
DSS.Circuit.SetActiveElement("GEN671")
DSS.Generators.kW()
```
it does not get the specified generator's kW rating attribute. 

Is there any function equivalent that I can use as follows? 
DSSObj.ActiveCircuit.CktElements('GEN680');   =>    API function  DSS.Circuit.SetActiveElement("GEN671")
DSSObj.ActiveCircuit.ActiveDSSElement.Properties('kW').Val  => ???

**Comment by PMeira** [comment]
Currently:
- you can get the properties of the active element from the `Properties` module -- `DSSObj.Properties.Value(number)` or `DSSObj.Properties.Value("name")`
- set the value by the same function `DSSObj.Properties.Value("name", "newvalue")` 
- list of properties from `Element.AllPropertyNames()`. 

Unfortunately the values are set and returned as strings and may need pre-/post-processing.

We'll add a move convenient in a few weeks. I just added an initial version (WIP) of the new API to DSS Python:
https://github.com/dss-extensions/dss_python/commit/3142194a699ffde66395975fc32e22eb0da3cce6

We also have a C++ version under testing internally, so porting it to Julia shouldn't be hard. I need to request and collect some feedback from other developers first though.

This new API allows inspecting all properties directly and also enables batch operations (read or modify a batch of elements at once) and will be used to implement further import/export features later.

I'll see if I can add JSON export support in the common library so we can use that in the meantime. I'll report back by tomorrow.

**Comment by PMeira** [comment]
> Currently:
> - you can get the properties of the active element from the `Properties` module -- `DSS.Properties.Value(number)` or `DSS.Properties.Value("name")`
> - set the value by the same function `DSS.Properties.Value("name", "newvalue")` 
> - list of properties from `DSS.Element.AllPropertyNames()`. 

To complement: this is for one generator. You need to iterate through the generators (`First()` and `Next()`, or  `Idx()` and `Count()`) and use `DSS.Properties.Value()` for each one.

**Comment by asavasci** [comment]
I got it thanks.

**Comment by PMeira** [comment]
The new JSON functions for DSS C-API worked great! I'll prepare the releases next weekend, even if the property help strings are not included.

You will soon be able to use it in the classic API though `DSS.Element.ToJSON()` and `DSS.ActiveClass.ToJSON()`,
and later through the new APIs.
