### ISSUE TITLE
Multiple DSS contexts

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/OpenDSSDirect.jl#81]
DSS C-API 0.12 supports creating multiple DSS instances that can be used separately, in threads, etc.

Should we expose this in ODD.jl? If so, what would be the best approach?

**Comment by kdheepak** [comment]
Where can I examples for the C API with contexts?

**Comment by tshort** [comment]
With multiple dispatch, it's easy to add an optional context that controls the DSS instance. 

```jl
# Normal usage (backwards compatible)
Circuit.SetActiveBus(bus)
v = Bus.Voltages()
# Calling a specific instance
Circuit.SetActiveBus(dss1, bus)
v = Bus.Voltages(dss1)
```
Here's how a definition could look:
```jl
    """Set active bus name"""
    function SetActiveBus(BusName::String)::Int
        return @checked Lib.Circuit_SetActiveBus(ACTIVECONTEXT, Cstring(pointer(BusName)))
    end
    function SetActiveBus(dss::TDSSContext, BusName::String)::Int
        return @checked Lib.Circuit_SetActiveBus(dss, Cstring(pointer(BusName)))
    end
```

**Comment by PMeira** [comment]
@kdheepak  I added a minimal C sample using OpenMP in https://github.com/dss-extensions/dss_capi/blob/master/examples/ctx_openmp.c
We should have some proper docs explaining the implementation and how it differs from the official OpenDSS by the end of next week. I have some older slides but they're not in English yet.

Currently every function that depends on the context was duplicated, so we have `Circuit_SetActiveBus` (without the context pointer) and `ctx_Circuit_SetActiveBus` (with the pointer). We could remove the old version without the context for 0.13, since it's planned to break and clean the API. Version 0.12 is still very backwards compatible.

> With multiple dispatch, it's easy to add an optional context that controls the DSS instance.

Thanks @tshort, I like the idea. It should be easy enough for users to adopt it too.

**Comment by PMeira** [comment]
I should have mentioned that in DSS Python, to avoid rewriting the code, I wrapped the `ctx_*` functions with `partial` to pre-bind the context:

https://github.com/dss-extensions/dss_python/blob/6e08549f1495e63ebdd72830d5ec8ec1d814e740/dss/_cffi_api_util.py#L67

[For C#](https://github.com/dss-extensions/dss_sharp/blob/41d9d8192709a18a6075d3f0fb5c9dce9b9188d6/src/dss_sharp_util.cs) and C++, it was easier to migrate to the `ctx_*` functions for other reasons. 

For compatibility, an initial context is always created and it's accessible via `ctx_Get_Prime()`. We can use that here and migrate to `ctx_*`, thus we would be free to remove the old API later (I'm handling ODD.py and DSS_MATLAB in the coming days).
