### ISSUE TITLE
DocStringExtensions Compatibility

### ISSUE THREAD

**Issue by CasBex** [dss-extensions/OpenDSSDirect.jl#92]
I'm trying to use OpenDSSDirect in tandem with the [FMIImport.jl](https://github.com/ThummeTo/FMIImport.jl). Due to some bugfixes I need the latest version 15.6 of that package, but this results in a non-resolvable environment due to the compatibility requirements between OpenDSS and [DocStringExtensions](https://github.com/JuliaDocs/DocStringExtensions.jl). 

If I install OpenDSSDirect locally and allow DocStringExtensions 0.9 in the `Project.toml` the conflict is resolved. OpenDSSDirect tests also pass in this case. Would it be possible to modify the `Project.toml`?

**Comment by PMeira** [comment]
Sure, I'll push a branch to run all tests on GitHub Actions. If all run OK, we'll get a new version soon.

**Comment by PMeira** [comment]
@CasBex All seems fine! As soon as the tests on the master branch finish, I'll register the new version.

By the way, someday we'd like to have a more direct integration with FMI in the DSS engine directly (so all projects on DSS-Extensions can benefit). Maybe later this year...

**Comment by CasBex** [comment]
Thanks for the quick response. That'll definitely be interesting to see
